<?php

namespace AppBundle\Repository;
use AppBundle\Entity\TickKey;
use Doctrine\ORM\NoResultException;

/**
 * TickKeyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TickKeyRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $name
     * @return TickKey
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findByNameOrNew(string $name): TickKey
    {
        try {
            $tickKey = $this->createQueryBuilder('k')
                ->andWhere('k.name = :name')
                ->setParameter('name', $name)
                ->setMaxResults(1)
                ->getQuery()
                ->getSingleResult();
        } catch (NoResultException $e) {
            $tickKey = new TickKey();
            $tickKey->setName($name);
        }
        return $tickKey;
    }
}
