<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Tick;
use AppBundle\Entity\TickKey;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityRepository;

/**
 * TickRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TickRepository extends EntityRepository
{
    /**
     * @param TickKey $key
     * @param $userId
     * @param int $limit
     * @param int $offset
     * @return Tick[]|ArrayCollection
     */
    public function findTicks(TickKey $key, $userId, $limit = 10, $offset = 0)
    {
        return $this->getTicksQuery($key, $userId)
            ->setFirstResult($offset)
            ->setMaxResults($limit)
            ->getResult();
    }

    /**
     * @param TickKey $key
     * @param $userId
     * @return Tick
     */
    public function findLatest(TickKey $key, $userId)
    {
        return $this->getTicksQuery($key, $userId)
            ->setMaxResults(1)
            ->getSingleResult();
    }

    /**
     * @param TickKey $key
     * @param $userId
     * @return \Doctrine\ORM\Query
     */
    protected function getTicksQuery(TickKey $key, $userId)
    {
        return $this->createQueryBuilder('t')
            ->andWhere('t.key = :key')
            ->andWhere('t.userId = :userId')
            ->orderBy('t.date', 'DESC')
            ->setParameters([
                'key' => $key,
                'userId' => $userId,
            ])
            ->getQuery();
    }
}
