<?php

namespace AppBundle\Repository;

/**
 * TickRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TickRepository extends \Doctrine\ORM\EntityRepository
{
}
