---
server:
    install: '1'
    timezone: Europe/Kiev
    locale: en_US.UTF-8
    packages: [mc, putty-tools]
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: dataservice.dev, ip: 192.168.33.30, memory: '512', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
nginx:
    install: '1'
    docroot: /vagrant/web
    servername: dataservice.dev
mysql:
    install: '1'
    root_password: admin
    database: dataservice
    user: dataservice
    password: password
    dump: ''
php:
    install: '1'
    ppa: php-7.0
    packages: [php7.0-cli, php7.0-intl, php7.0-json, php7.0-opcache, php7.0-mysql]

